#!/usr/bin/env ruby

require "bundler/inline"

gemfile true do
  source "https://rubygems.org"
  gem "httparty"
end

require_relative './lib/parser'
require_relative './lib/reader'

# puts "** #{ARGF}"
# ARGV[1].each_line do |e|
#   puts e
# end

TYPE = ['-r', '-p']
ERR_MSG = "Error:: Unknow parameters. Please follow this"

if ARGV.size > 3 && ARGV.size < 2
  p ERR_MSG
else
  if TYPE.include?(ARGV[0])
    case ARGV.size
      when 2
        then Reader::start(ARGV[1])
      when 3
        then Parser::start(ARGV[1], ARGV[2])
    end
  else
    p ERR_MSG 
  end
end