#!/usr/bin/env ruby

require "bundler/inline"

gemfile true do
  source "https://rubygems.org"
  gem "httparty"
end

require_relative './lib/parser'
require_relative './lib/reader'

TYPE = ['-r', '-p']
ERR_MSG = "Error:: Unknow parameters. Please follow this:
  - ./cli -r clients.csv #for reading CSV
  - ./cli -p clients.csv output.csv #for parsing and validating CSV
"

if ARGV.size > 3 && ARGV.size < 2
  puts ERR_MSG
else
  if TYPE.include?(ARGV[0])
    case ARGV.size
      when 2
        then Reader::start(ARGV[1])
      when 3
        then Parser::start(ARGV[1], ARGV[2])
    end
  else
    puts ERR_MSG 
  end
end